name: Build Documentation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install DocFX
      run: |
        wget https://github.com/dotnet/docfx/releases/download/v2.70/docfx.zip
        unzip docfx.zip -d docfx
        chmod +x ./docfx/docfx

    - name: Build Documentation
      run: |
        ./docfx/docfx docfx.json

    - name: Upload Documentation Artifact
      uses: actions/upload-artifact@v3
      with:
        name: site-content
        path: _site
